linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - vet
    - revive
    - unused
    - misspell
  disable:
    - errcheck

issues:
  include:
    - EXC0002

run:
  timeout: 2m
